In [1]:
import numpy as np
from scipy.stats import multivariate_normal

In [48]:
n_positive = 100
n_negative = 50

positive = np.random.multivariate_normal([10, 5], [[5, 0], [0, 4]], n_positive)
negative = np.random.multivariate_normal([3, 6], [[8, 0], [0, 7]], n_negative)

In [49]:
X = np.concatenate([positive, negative])

In [50]:
y = np.concatenate([np.ones(n_positive), np.zeros(n_negative)])

In [51]:
positive_mean = positive.mean(axis=0)
negative_mean = negative.mean(axis=0)

In [52]:
positive_mean

array([10.26224629,  5.05334709])

In [53]:
negative_mean

array([3.16150108, 5.67822584])

In [54]:
X_mean = np.stack([positive_mean if i else negative_mean for i in y])

In [55]:
covariance = np.dot((X - X_mean).T,X - X_mean) / len(y)
covariance

array([[ 5.62331995, -0.67556098],
       [-0.67556098,  4.36062605]])

In [64]:
sample_idx = np.random.randint(len(y))
sample = X[sample_idx]

In [79]:
px_y1 = multivariate_normal.pdf(sample, positive_mean, covariance)

px_y0 = multivariate_normal.pdf(sample, negative_mean, covariance)

py1 = y.mean()

py0 = 1 - py1

In [80]:
# positive
px_y1 * py1 / (px_y1 * py1 + px_y0 * py0)

0.9999489279824457

In [81]:
# negative
px_y0 * py0 / (px_y1 * py1 + px_y0 * py0)

5.107201755424094e-05

In [82]:
y[sample_idx]

1.0

In [83]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [84]:
clf = LinearDiscriminantAnalysis(store_covariance=True)
clf.fit(X, y)

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                           solver='svd', store_covariance=True, tol=0.0001)

In [71]:
clf.coef_

array([[1.25221544, 0.05260732]])

In [72]:
clf.means_

array([[ 3.16150108,  5.67822584],
       [10.26224629,  5.05334709]])

In [73]:
clf.covariance_

array([[ 5.62331995, -0.67556098],
       [-0.67556098,  4.36062605]])

In [74]:
clf.predict_proba(sample.reshape(1, 2))

array([[5.77285064e-05, 9.99942271e-01]])

In [85]:
clf.decision_function(sample.reshape(1, 2))

array([9.75970173])